// Copyright 2025 The FluidMarkdown Authors. All rights reserved.
// Use of this source code is governed by a Apache 2.0 license that can be
// found in the LICENSE file.

/**
 * markdown-it-emoji
 * @home   : https://github.com/markdown-it/markdown-it-emoji
 * @branch : master
 * @commit : bdd07260f080e4d3d812928f3eb0b00883e4e71b
 */

import full from './markdown-it-emoji';
import bare from './markdown-it-emoji-bare';
import light from './markdown-it-emoji-light';

export { bare, light };
export default full;