// Copyright 2025 The FluidMarkdown Authors. All rights reserved.
// Use of this source code is governed by a Apache 2.0 license that can be
// found in the LICENSE file.

/**
 * markdown-it-footnote
 * @home   : https://github.com/markdown-it/markdown-it-footnote
 * @branch : master
 * @commit : fe6c169c72b9f4d6656b10aa449128456f5a990e
 */

import plugin from './markdown-it-footnote';
export default plugin;