// Copyright 2025 The FluidMarkdown Authors. All rights reserved.
// Use of this source code is governed by a Apache 2.0 license that can be
// found in the LICENSE file.

/**
 * markdown-it-task-lists
 * @home   : https://github.com/revin/markdown-it-task-lists
 * @branch : master
 * @commit : 1e68dd719b9c68be65fdb74f5c5e6d94d214447e
 */

import plugin from './markdown-it-task-lists';
export default plugin;
export interface IPluginTaskListOption {
  enabled?: boolean;
}